import { llmGateway } from './llm/gateway.mjs';
import { buildPreviewHTML } from './buildPreview.mjs';
import { SYSTEM_BUILDER_PROMPT, INTENT_SYSTEM_PROMPT, REPAIR_SYSTEM_PROMPT } from './prompts/systemBuilderPrompt.mjs';

const STEPS = [
  { name: 'Intent Parser', description: 'Understanding product intent...' },
  { name: 'Builder Agent', description: 'Generating working React files...' },
  { name: 'Preview Compiler', description: 'Compiling live preview...' },
  { name: 'Repair Agent', description: 'Repairing compile issues...' },
];

function sendAgent(onEvent, index, status, description) {
  const step = STEPS[index];
  onEvent?.({
    type: 'agent',
    agent: step.name,
    index,
    total: STEPS.length,
    status,
    description,
  });
}

function sendThinking(onEvent, agent, thinkingLine) {
  onEvent?.({ type: 'thinking', agent, thinkingLine });
}

function parseIntent(content, prompt) {
  try {
    return llmGateway.parseJSON(content);
  } catch {
    return {
      intent: 'create',
      appType: 'web app',
      requirements: [prompt],
      constraints: ['React', 'TypeScript', 'Tailwind CSS'],
      targetFiles: ['src/App.tsx'],
    };
  }
}

function normalizeFiles(files, prompt, rawContent) {
  const clean = (Array.isArray(files) ? files : [])
    .filter(file => file?.path && typeof file.content === 'string')
    .map(file => ({
      path: file.path.replace(/^\/+/, '').replace(/\\/g, '/'),
      content: file.content.trim(),
    }));

  if (clean.some(file => file.path === 'src/App.tsx' || file.path === 'src/App.jsx')) {
    return clean;
  }

  clean.unshift({
    path: 'src/App.tsx',
    content: `export default function App() {
  return (
    <main className="min-h-screen bg-[#0a0a0b] text-white flex items-center justify-center p-8">
      <section className="max-w-4xl rounded-3xl border border-blue-500/20 bg-zinc-950 p-10 shadow-2xl">
        <p className="text-sm text-blue-300 mb-4">Generated by Huggy Builder</p>
        <h1 className="text-5xl font-black mb-4">${prompt.replace(/`/g, '')}</h1>
        <p className="text-zinc-400">The model response was normalized into a safe working preview.</p>
        <pre className="mt-6 max-h-56 overflow-auto rounded-2xl bg-black/40 p-4 text-xs text-zinc-300 whitespace-pre-wrap">${rawContent.slice(0, 800).replace(/`/g, '')}</pre>
      </section>
    </main>
  );
}
`,
  });

  return clean;
}

async function runLLM(agentName, prompt, systemPrompt, onEvent, index) {
  sendAgent(onEvent, index, 'active', STEPS[index].description);
  const result = await llmGateway.streamGenerate(agentName, prompt, {
    onThinking: line => sendThinking(onEvent, STEPS[index].name, line),
    onChunk: chunk => onEvent?.({ type: 'reply', agent: STEPS[index].name, replyChunk: chunk }),
  }, systemPrompt);

  if (!result.success) {
    throw new Error(result.error || `${STEPS[index].name} failed`);
  }

  sendAgent(onEvent, index, 'completed', `${STEPS[index].name} completed`);
  return result.content;
}

export async function runLovablePipeline(prompt, options = {}) {
  const onEvent = options.onEvent;
  const existingFiles = Array.isArray(options.files) ? options.files : [];

  onEvent?.({ type: 'connected', message: 'Lovable-like pipeline connected' });

  const intentContent = await runLLM(
    'Product Manager',
    `User prompt: ${prompt}`,
    INTENT_SYSTEM_PROMPT,
    onEvent,
    0,
  );
  const intent = parseIntent(intentContent, prompt);

  const context = [
    `# USER REQUEST\n${prompt}`,
    `# INTENT\n${JSON.stringify(intent, null, 2)}`,
    existingFiles.length ? `# EXISTING FILES\n${existingFiles.map(f => `file:${f.path}\n${f.content}`).join('\n---\n')}` : '',
  ].filter(Boolean).join('\n\n');

  const builderContent = await runLLM(
    'Coder Agent',
    `${context}\n\nGenerate the app now.`,
    SYSTEM_BUILDER_PROMPT,
    onEvent,
    1,
  );

  let files = normalizeFiles(llmGateway.parseFiles(builderContent), prompt, builderContent);
  let previewError = null;

  for (let attempt = 0; attempt < 3; attempt++) {
    sendAgent(onEvent, 2, 'active', attempt === 0 ? 'Compiling generated app...' : `Recompiling after repair (${attempt}/2)...`);
    try {
      await buildPreviewHTML(files);
      sendAgent(onEvent, 2, 'completed', 'Preview compiled successfully');
      previewError = null;
      break;
    } catch (error) {
      previewError = error instanceof Error ? error.message : String(error);
      sendThinking(onEvent, 'Preview Compiler', previewError);
      sendAgent(onEvent, 2, 'completed', 'Preview compiler reported errors');

      if (attempt >= 2) break;

      const repairPrompt = [
        `# ORIGINAL USER REQUEST\n${prompt}`,
        `# PREVIEW ERROR\n${previewError}`,
        `# FILES TO FIX\n${files.map(f => `\`\`\`file:${f.path}\n${f.content}\n\`\`\``).join('\n\n')}`,
      ].join('\n\n');

      const repairContent = await runLLM(
        'Coder Agent',
        repairPrompt,
        REPAIR_SYSTEM_PROMPT,
        onEvent,
        3,
      );
      const repairedFiles = llmGateway.parseFiles(repairContent);
      if (repairedFiles.length) {
        const byPath = new Map(files.map(file => [file.path, file]));
        for (const file of repairedFiles) byPath.set(file.path, file);
        files = normalizeFiles([...byPath.values()], prompt, repairContent);
      }
    }
  }

  if (previewError) {
    onEvent?.({ type: 'error', message: `Preview still has errors after repair: ${previewError}` });
  }

  return {
    success: true,
    files,
    reply: previewError
      ? `Generated files, but preview still needs attention: ${previewError}`
      : '✅ Application generated and compiled successfully.',
    meta: {
      pmPlan: { projectName: intent.appType || 'Generated App', complexity: 'simple' },
      review: { score: previewError ? 70 : 95, approved: !previewError },
      secReport: { score: 90, approved: true },
    },
  };
}
